unit UDMBlocagem;

interface

uses
  SysUtils, Classes, FMTBcd, DB, DBClient, Provider, SqlExpr;

type
  TDMBlocagem = class(TDataModule)
    sdsContrato: TSQLDataSet;
    dspContrato: TDataSetProvider;
    cdsContrato: TClientDataSet;
    dsContrato: TDataSource;
    dsProdutos: TDataSource;
    sdsContratoID_CLIENTE: TIntegerField;
    sdsContratoID_ASSINATURA: TIntegerField;
    sdsContratoDTCONTRATO: TDateField;
    sdsContratoDTCOBRANCA: TDateField;
    sdsContratoQTD: TFloatField;
    sdsContratoPERIODO: TStringField;
    sdsContratoDTENCERRAMENTO: TDateField;
    cdsContratoID_CLIENTE: TIntegerField;
    cdsContratoID_ASSINATURA: TIntegerField;
    cdsContratoDTCONTRATO: TDateField;
    cdsContratoDTCOBRANCA: TDateField;
    cdsContratoQTD: TFloatField;
    cdsContratoPERIODO: TStringField;
    cdsContratoDTENCERRAMENTO: TDateField;
    dsEmpresa: TDataSource;
    sdsContratoID_PERIODO: TIntegerField;
    cdsContratoID_PERIODO: TIntegerField;
    sdsContratoAPEL_EBS: TStringField;
    cdsContratoAPEL_EBS: TStringField;
    sdsContratoVLR_UNITARIO: TFloatField;
    sdsContratoVLR_TOTAL: TFloatField;
    cdsContratoVLR_UNITARIO: TFloatField;
    cdsContratoVLR_TOTAL: TFloatField;
    sdsContratoGEROU_DUPLICATA: TStringField;
    cdsContratoGEROU_DUPLICATA: TStringField;
    mBlocagem: TClientDataSet;
    dsmBlocagem: TDataSource;
    mBlocagemTipo: TStringField;
    mBlocagemNome: TStringField;
    mBlocagemEndereco: TStringField;
    mBlocagemBairro: TStringField;
    mBlocagemCidade: TStringField;
    mBlocagemUF: TStringField;
    mBlocagemCep: TStringField;
    mBlocagemDtEncerramento: TDateField;
    mBlocagemDtInicio: TDateField;
    mBlocagemNumContrato: TStringField;
    sdsContratoID: TFMTBCDField;
    sdsContratoNUM_CONTRATO: TStringField;
    cdsContratoID: TFMTBCDField;
    cdsContratoNUM_CONTRATO: TStringField;
    sdsAssinatura: TSQLDataSet;
    sdsAssinaturaID: TIntegerField;
    sdsAssinaturaNOME: TStringField;
    sdsAssinaturaOBS: TMemoField;
    sdsAssinaturaVALOR: TFloatField;
    sdsAssinaturaDTATUALIZACAO_VLR: TDateField;
    sdsAssinaturaID_PERIODO: TIntegerField;
    dspAssinatura: TDataSetProvider;
    cdsAssinatura: TClientDataSet;
    cdsAssinaturaID: TIntegerField;
    cdsAssinaturaNOME: TStringField;
    cdsAssinaturaOBS: TMemoField;
    cdsAssinaturaVALOR: TFloatField;
    cdsAssinaturaDTATUALIZACAO_VLR: TDateField;
    cdsAssinaturaID_PERIODO: TIntegerField;
    dsAssinatura: TDataSource;
    sdsContratoNOMEASSINATURA: TStringField;
    cdsContratoNOMEASSINATURA: TStringField;
    mBlocagemNomeAssinatura: TStringField;
    sdsControle_Estoque: TSQLDataSet;
    dspControle_Estoque: TDataSetProvider;
    cdsControle_Estoque: TClientDataSet;
    dsControle_Estoque: TDataSource;
    sdsControle_EstoqueID: TIntegerField;
    sdsControle_EstoqueNUM_CONTRATO: TStringField;
    sdsControle_EstoqueDTREFERENCIA: TDateField;
    cdsControle_EstoqueID: TIntegerField;
    cdsControle_EstoqueNUM_CONTRATO: TStringField;
    cdsControle_EstoqueDTREFERENCIA: TDateField;
    sdsControle_EstoqueMES: TIntegerField;
    sdsControle_EstoqueANO: TIntegerField;
    cdsControle_EstoqueMES: TIntegerField;
    cdsControle_EstoqueANO: TIntegerField;
    dsAssinatura_Mestre: TDataSource;
    sdsAssinatura_Livro: TSQLDataSet;
    sdsAssinatura_LivroID: TIntegerField;
    sdsAssinatura_LivroITEM: TIntegerField;
    sdsAssinatura_LivroQTD: TIntegerField;
    sdsAssinatura_LivroCOD_PRODUTO_EBS: TStringField;
    sdsAssinatura_LivroNOME_PRODUTO_EBS: TStringField;
    cdsAssinatura_Livro: TClientDataSet;
    cdsAssinaturasdsAssinatura_Livro: TDataSetField;
    cdsAssinatura_LivroID: TIntegerField;
    cdsAssinatura_LivroITEM: TIntegerField;
    cdsAssinatura_LivroQTD: TIntegerField;
    cdsAssinatura_LivroCOD_PRODUTO_EBS: TStringField;
    cdsAssinatura_LivroNOME_PRODUTO_EBS: TStringField;
    mBlocagemID_Assinatura: TIntegerField;
    mBlocagemApel_EBS: TStringField;
    sdsEstMovimento: TSQLDataSet;
    sdsEstMovimentoCODLOC: TStringField;
    sdsEstMovimentoCODPRO: TStringField;
    sdsEstMovimentoDATMOV: TSQLTimeStampField;
    sdsEstMovimentoSEQMOV: TIntegerField;
    sdsEstMovimentoCODPRJ: TIntegerField;
    sdsEstMovimentoNRODOC: TIntegerField;
    sdsEstMovimentoTIPREG: TStringField;
    sdsEstMovimentoCODFOR: TStringField;
    sdsEstMovimentoSEQITE: TIntegerField;
    sdsEstMovimentoENTSAI: TStringField;
    sdsEstMovimentoQTDMOV: TFloatField;
    sdsEstMovimentoVLRMOV: TFloatField;
    sdsEstMovimentoQTDANT: TFloatField;
    sdsEstMovimentoQTDAPO: TFloatField;
    sdsEstMovimentoORIMOV: TStringField;
    sdsEstMovimentoCODCCU: TIntegerField;
    sdsEstMovimentoCODCTF: TIntegerField;
    sdsEstMovimentoHORMOV: TIntegerField;
    sdsEstMovimentoMIGMOV: TBooleanField;
    sdsEstMovimentoCUSPRO: TFloatField;
    sdsEstMovimentoANOASS: TIntegerField;
    sdsEstMovimentoVLRANT: TFloatField;
    sdsEstMovimentoVLRAPOS: TFloatField;
    sdsEstMovimentoCUSTMEDPRO: TFloatField;
    sdsEstMovimentoregistro_integrado: TBooleanField;
    sdsEstMovimentodata_integracao: TSQLTimeStampField;
    dspEstMovimento: TDataSetProvider;
    cdsEstMovimento: TClientDataSet;
    cdsEstMovimentoCODLOC: TStringField;
    cdsEstMovimentoCODPRO: TStringField;
    cdsEstMovimentoDATMOV: TSQLTimeStampField;
    cdsEstMovimentoSEQMOV: TIntegerField;
    cdsEstMovimentoCODPRJ: TIntegerField;
    cdsEstMovimentoNRODOC: TIntegerField;
    cdsEstMovimentoTIPREG: TStringField;
    cdsEstMovimentoCODFOR: TStringField;
    cdsEstMovimentoSEQITE: TIntegerField;
    cdsEstMovimentoENTSAI: TStringField;
    cdsEstMovimentoQTDMOV: TFloatField;
    cdsEstMovimentoVLRMOV: TFloatField;
    cdsEstMovimentoQTDANT: TFloatField;
    cdsEstMovimentoQTDAPO: TFloatField;
    cdsEstMovimentoORIMOV: TStringField;
    cdsEstMovimentoCODCCU: TIntegerField;
    cdsEstMovimentoCODCTF: TIntegerField;
    cdsEstMovimentoHORMOV: TIntegerField;
    cdsEstMovimentoMIGMOV: TBooleanField;
    cdsEstMovimentoCUSPRO: TFloatField;
    cdsEstMovimentoANOASS: TIntegerField;
    cdsEstMovimentoVLRANT: TFloatField;
    cdsEstMovimentoVLRAPOS: TFloatField;
    cdsEstMovimentoCUSTMEDPRO: TFloatField;
    cdsEstMovimentoregistro_integrado: TBooleanField;
    cdsEstMovimentodata_integracao: TSQLTimeStampField;
    sdsProdutos: TSQLDataSet;
    dspProdutos: TDataSetProvider;
    cdsProdutos: TClientDataSet;
    sdsProdutosCodigo: TStringField;
    sdsProdutosTipo: TStringField;
    sdsProdutosLinha01: TStringField;
    sdsProdutosLinha02: TStringField;
    sdsProdutosLinha03: TStringField;
    sdsProdutosMarca: TStringField;
    sdsProdutosUnidade: TStringField;
    sdsProdutosUnidadeEntrada: TStringField;
    sdsProdutosUnidadeAuxiliar: TStringField;
    sdsProdutosUnidadeAuxiliar1: TStringField;
    sdsProdutosUnidadedeCompra: TStringField;
    sdsProdutosAtacadosomentesemaiorque: TIntegerField;
    sdsProdutosPesoLquido: TFloatField;
    sdsProdutosLocalizaodoProduto: TStringField;
    sdsProdutosDiasparaReposio: TSmallintField;
    sdsProdutosMesesdegarantia: TSmallintField;
    sdsProdutosGrupo: TIntegerField;
    sdsProdutosSubgrupo: TIntegerField;
    sdsProdutosSituaodoProduto: TStringField;
    sdsProdutosSituaoTributria: TStringField;
    sdsProdutosCdigodoNCM: TStringField;
    sdsProdutosLetradoNCM: TStringField;
    sdsProdutosReal: TFloatField;
    sdsProdutosVirtual: TFloatField;
    sdsProdutosMnimo: TFloatField;
    sdsProdutosMximo: TFloatField;
    sdsProdutosMdiadeVendas: TFloatField;
    sdsProdutosMdiadeFabricao: TFloatField;
    sdsProdutosLoteMnimodeCompras: TFloatField;
    sdsProdutosLoteMnimodeVendas: TFloatField;
    sdsProdutosLoteMnimodeFabricao: TFloatField;
    sdsProdutosValordeCompra: TFloatField;
    sdsProdutosValordeVenda: TFloatField;
    sdsProdutosMargemdeVenda: TFloatField;
    sdsProdutosVendaAtacado: TFloatField;
    sdsProdutosVendaVarejo: TFloatField;
    sdsProdutosMargemAtacado: TFloatField;
    sdsProdutosMargemVarejo: TFloatField;
    sdsProdutosValordeTransferncia: TFloatField;
    sdsProdutosValorPromoo: TFloatField;
    sdsProdutosValidadedaPromoo: TSQLTimeStampField;
    sdsProdutosValorPromooAtacado: TFloatField;
    sdsProdutosValidadedaPromooAtacado: TSQLTimeStampField;
    sdsProdutosValorPromooVarejo: TFloatField;
    sdsProdutosValidadedaPromooVarejo: TSQLTimeStampField;
    sdsProdutosltimaAtualizaodoProduto: TSQLTimeStampField;
    sdsProdutosltimaAtualizaodeVenda: TSQLTimeStampField;
    sdsProdutosQuantidadeporVolume: TFloatField;
    sdsProdutosNmerodoDesenho: TStringField;
    sdsProdutosEspecificaesTcnicas: TMemoField;
    sdsProdutosCdigodeBarras: TStringField;
    sdsProdutosListadePreos: TBooleanField;
    sdsProdutosComisso: TFloatField;
    sdsProdutosMoedaVenda: TStringField;
    sdsProdutosCondiodePagamento: TSmallintField;
    sdsProdutosMargemdeVendaSubstituioTr: TFloatField;
    sdsProdutosValordosMateriais: TFloatField;
    sdsProdutosValordaModeObra: TFloatField;
    sdsProdutosCentro: TIntegerField;
    sdsProdutosOutrasInformaes01: TStringField;
    sdsProdutosOutrasInformaes02: TStringField;
    sdsProdutosOutrasInformaes03: TStringField;
    sdsProdutosOutrasInformaes04: TStringField;
    sdsProdutosOutrasInformaes05: TStringField;
    sdsProdutosOutrasInformaes06: TStringField;
    sdsProdutosOutrasInformaes07: TStringField;
    sdsProdutosOutrasInformaes08: TStringField;
    sdsProdutosOutrasInformaes09: TStringField;
    sdsProdutosOutrasInformaes10: TStringField;
    sdsProdutosArquivocomEspecificaoTcni: TStringField;
    sdsProdutosFatordeConversodeUnidadep: TFloatField;
    sdsProdutosObrigatrioLicena: TBooleanField;
    sdsProdutosFoto: TBlobField;
    sdsProdutosDatadoInventrio: TSQLTimeStampField;
    sdsProdutosVendedor01: TSmallintField;
    sdsProdutosValordeCompraOriginal: TFloatField;
    sdsProdutosValordeDescontonaCompra: TFloatField;
    sdsProdutosUnidadeVlrVenda: TStringField;
    sdsProdutosArea: TFloatField;
    sdsProdutosCODIPI: TIntegerField;
    sdsProdutosLOCPAD: TStringField;
    sdsProdutosCUSPRO: TFloatField;
    sdsProdutosPerDmx: TFloatField;
    sdsProdutosICMVEN: TFloatField;
    sdsProdutosICMCOM: TFloatField;
    sdsProdutosUMEPRO: TStringField;
    sdsProdutoscd_conta_contabil: TIntegerField;
    sdsProdutoscd_formacalculo_icmsst: TIntegerField;
    sdsProdutospr_aliquota_int_icmsst: TFMTBCDField;
    sdsProdutosultimo_lote: TStringField;
    sdsProdutosultima_serie: TStringField;
    sdsProdutospeso_embalagem: TFMTBCDField;
    sdsProdutossit_trib_ipi: TStringField;
    sdsProdutossit_trib_pis: TStringField;
    sdsProdutossit_trib_cofins: TStringField;
    sdsProdutosproduto_configuravel: TBooleanField;
    sdsProdutosprodpeso: TStringField;
    sdsProdutosdata_integracao: TSQLTimeStampField;
    sdsProdutosaliquota_diferenciada: TFloatField;
    sdsProdutosconteudo_importacao: TFloatField;
    sdsProdutosproduto_importacao: TBooleanField;
    sdsProdutosgera_fci: TBooleanField;
    sdsProdutosnr_controle_fci: TStringField;
    cdsProdutosCodigo: TStringField;
    cdsProdutosTipo: TStringField;
    cdsProdutosLinha01: TStringField;
    cdsProdutosLinha02: TStringField;
    cdsProdutosLinha03: TStringField;
    cdsProdutosMarca: TStringField;
    cdsProdutosUnidade: TStringField;
    cdsProdutosUnidadeEntrada: TStringField;
    cdsProdutosUnidadeAuxiliar: TStringField;
    cdsProdutosUnidadeAuxiliar1: TStringField;
    cdsProdutosUnidadedeCompra: TStringField;
    cdsProdutosAtacadosomentesemaiorque: TIntegerField;
    cdsProdutosPesoLquido: TFloatField;
    cdsProdutosLocalizaodoProduto: TStringField;
    cdsProdutosDiasparaReposio: TSmallintField;
    cdsProdutosMesesdegarantia: TSmallintField;
    cdsProdutosGrupo: TIntegerField;
    cdsProdutosSubgrupo: TIntegerField;
    cdsProdutosSituaodoProduto: TStringField;
    cdsProdutosSituaoTributria: TStringField;
    cdsProdutosCdigodoNCM: TStringField;
    cdsProdutosLetradoNCM: TStringField;
    cdsProdutosReal: TFloatField;
    cdsProdutosVirtual: TFloatField;
    cdsProdutosMnimo: TFloatField;
    cdsProdutosMximo: TFloatField;
    cdsProdutosMdiadeVendas: TFloatField;
    cdsProdutosMdiadeFabricao: TFloatField;
    cdsProdutosLoteMnimodeCompras: TFloatField;
    cdsProdutosLoteMnimodeVendas: TFloatField;
    cdsProdutosLoteMnimodeFabricao: TFloatField;
    cdsProdutosValordeCompra: TFloatField;
    cdsProdutosValordeVenda: TFloatField;
    cdsProdutosMargemdeVenda: TFloatField;
    cdsProdutosVendaAtacado: TFloatField;
    cdsProdutosVendaVarejo: TFloatField;
    cdsProdutosMargemAtacado: TFloatField;
    cdsProdutosMargemVarejo: TFloatField;
    cdsProdutosValordeTransferncia: TFloatField;
    cdsProdutosValorPromoo: TFloatField;
    cdsProdutosValidadedaPromoo: TSQLTimeStampField;
    cdsProdutosValorPromooAtacado: TFloatField;
    cdsProdutosValidadedaPromooAtacado: TSQLTimeStampField;
    cdsProdutosValorPromooVarejo: TFloatField;
    cdsProdutosValidadedaPromooVarejo: TSQLTimeStampField;
    cdsProdutosltimaAtualizaodoProduto: TSQLTimeStampField;
    cdsProdutosltimaAtualizaodeVenda: TSQLTimeStampField;
    cdsProdutosQuantidadeporVolume: TFloatField;
    cdsProdutosNmerodoDesenho: TStringField;
    cdsProdutosEspecificaesTcnicas: TMemoField;
    cdsProdutosCdigodeBarras: TStringField;
    cdsProdutosListadePreos: TBooleanField;
    cdsProdutosComisso: TFloatField;
    cdsProdutosMoedaVenda: TStringField;
    cdsProdutosCondiodePagamento: TSmallintField;
    cdsProdutosMargemdeVendaSubstituioTr: TFloatField;
    cdsProdutosValordosMateriais: TFloatField;
    cdsProdutosValordaModeObra: TFloatField;
    cdsProdutosCentro: TIntegerField;
    cdsProdutosOutrasInformaes01: TStringField;
    cdsProdutosOutrasInformaes02: TStringField;
    cdsProdutosOutrasInformaes03: TStringField;
    cdsProdutosOutrasInformaes04: TStringField;
    cdsProdutosOutrasInformaes05: TStringField;
    cdsProdutosOutrasInformaes06: TStringField;
    cdsProdutosOutrasInformaes07: TStringField;
    cdsProdutosOutrasInformaes08: TStringField;
    cdsProdutosOutrasInformaes09: TStringField;
    cdsProdutosOutrasInformaes10: TStringField;
    cdsProdutosArquivocomEspecificaoTcni: TStringField;
    cdsProdutosFatordeConversodeUnidadep: TFloatField;
    cdsProdutosObrigatrioLicena: TBooleanField;
    cdsProdutosFoto: TBlobField;
    cdsProdutosDatadoInventrio: TSQLTimeStampField;
    cdsProdutosVendedor01: TSmallintField;
    cdsProdutosValordeCompraOriginal: TFloatField;
    cdsProdutosValordeDescontonaCompra: TFloatField;
    cdsProdutosUnidadeVlrVenda: TStringField;
    cdsProdutosArea: TFloatField;
    cdsProdutosCODIPI: TIntegerField;
    cdsProdutosLOCPAD: TStringField;
    cdsProdutosCUSPRO: TFloatField;
    cdsProdutosPerDmx: TFloatField;
    cdsProdutosICMVEN: TFloatField;
    cdsProdutosICMCOM: TFloatField;
    cdsProdutosUMEPRO: TStringField;
    cdsProdutoscd_conta_contabil: TIntegerField;
    cdsProdutoscd_formacalculo_icmsst: TIntegerField;
    cdsProdutospr_aliquota_int_icmsst: TFMTBCDField;
    cdsProdutosultimo_lote: TStringField;
    cdsProdutosultima_serie: TStringField;
    cdsProdutospeso_embalagem: TFMTBCDField;
    cdsProdutossit_trib_ipi: TStringField;
    cdsProdutossit_trib_pis: TStringField;
    cdsProdutossit_trib_cofins: TStringField;
    cdsProdutosproduto_configuravel: TBooleanField;
    cdsProdutosprodpeso: TStringField;
    cdsProdutosdata_integracao: TSQLTimeStampField;
    cdsProdutosaliquota_diferenciada: TFloatField;
    cdsProdutosconteudo_importacao: TFloatField;
    cdsProdutosproduto_importacao: TBooleanField;
    cdsProdutosgera_fci: TBooleanField;
    cdsProdutosnr_controle_fci: TStringField;
    sdsEmpresa: TSQLDataSet;
    sdsEmpresaNomeCliente: TStringField;
    sdsEmpresaApel: TStringField;
    sdsEmpresaCdigo: TSmallintField;
    sdsEmpresaTipo: TStringField;
    sdsEmpresaEndereo: TStringField;
    sdsEmpresaBairro: TStringField;
    sdsEmpresaCEP: TStringField;
    sdsEmpresaCidade: TStringField;
    sdsEmpresaEstado: TStringField;
    sdsEmpresaPessoa: TStringField;
    sdsEmpresaCNPJCPF: TStringField;
    sdsEmpresaIEstRG: TStringField;
    sdsEmpresaFone: TStringField;
    sdsEmpresaRamal: TStringField;
    sdsEmpresacd_pais: TStringField;
    sdsEmpresacd_municipio_ibge: TIntegerField;
    dspEmpresa: TDataSetProvider;
    cdsEmpresa: TClientDataSet;
    cdsEmpresaNomeCliente: TStringField;
    cdsEmpresaApel: TStringField;
    cdsEmpresaCdigo: TSmallintField;
    cdsEmpresaTipo: TStringField;
    cdsEmpresaEndereo: TStringField;
    cdsEmpresaBairro: TStringField;
    cdsEmpresaCEP: TStringField;
    cdsEmpresaCidade: TStringField;
    cdsEmpresaEstado: TStringField;
    cdsEmpresaPessoa: TStringField;
    cdsEmpresaCNPJCPF: TStringField;
    cdsEmpresaIEstRG: TStringField;
    cdsEmpresaFone: TStringField;
    cdsEmpresaRamal: TStringField;
    cdsEmpresacd_pais: TStringField;
    cdsEmpresacd_municipio_ibge: TIntegerField;
    sdsProdutosNomeProduto: TStringField;
    cdsProdutosNomeProduto: TStringField;
    mBlocagemNum_Endereco: TStringField;
    sdsEmpresanro_endereco: TStringField;
    cdsEmpresanro_endereco: TStringField;
    mBlocagemGerou_Pre_Contrato: TStringField;
    sdsContratoPRE_CONTRATO: TStringField;
    sdsContratoENCERRADO: TStringField;
    sdsContratoGEROU_PRE_CONTRATO: TStringField;
    cdsContratoPRE_CONTRATO: TStringField;
    cdsContratoENCERRADO: TStringField;
    cdsContratoGEROU_PRE_CONTRATO: TStringField;
    mBlocagemEncerrado: TStringField;
    mBlocagemPre_Contrato: TStringField;
    mBlocagemDTCobranca: TDateField;
    sdsContratoNUM_CONTRATO_ANT: TStringField;
    cdsContratoNUM_CONTRATO_ANT: TStringField;
    mBlocagemNum_Contrato_Ant: TStringField;
    qPessoa: TSQLQuery;
    qPessoaNOME: TStringField;
    qPessoaEMAIL_NFE: TStringField;
    mBlocagemEmail: TStringField;
    mBlocagemID_Cliente: TIntegerField;
    procedure DataModuleCreate(Sender: TObject);
    procedure dspEstMovimentoGetTableName(Sender: TObject;
      DataSet: TDataSet; var TableName: String);
  private
    { Private declarations }

  public
    { Public declarations }
    procedure prc_Abrir_EstMovimento;

  end;

var
  DMBlocagem: TDMBlocagem;
  ctEmpresasEBS : String;
  ctContrato    : String;
  ctEstMovimento : String;


implementation

uses DmdDatabase, DmdDatabase_EBS;

{$R *.dfm}

{ TDMCadPais }

procedure TDMBlocagem.DataModuleCreate(Sender: TObject);
begin
  ctEmpresasEBS  := sdsEmpresa.CommandText;
  ctContrato     := sdsContrato.CommandText;
  ctEstMovimento := sdsEstMovimento.CommandText;
  cdsProdutos.Open;
  cdsAssinatura.Open;
end;

procedure TDMBlocagem.prc_Abrir_EstMovimento;
begin
  cdsEstMovimento.Close;
  sdsEstMovimento.CommandText := ctEstMovimento
                               + ' WHERE CODLOC = ' + QuotedStr('99999');
  cdsEstMovimento.Open;
end;

procedure TDMBlocagem.dspEstMovimentoGetTableName(Sender: TObject;
  DataSet: TDataSet; var TableName: String);
begin
  TableName := 'ESTMOVIMENTO';
end;

end.
